name: Push Docker Hub image to GHCR

on:
  workflow_dispatch:
    inputs:
      ghcr_username:
        description: 'GitHub username for GHCR'
        required: true
        default: 'your-github-username'
      ghcr_image:
        description: 'GHCR image name'
        required: true
        default: 'your-image-name'
      ghcr_tag:
        description: 'GHCR image tag'
        required: false
        default: 'latest'

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR using PAT
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.event.inputs.ghcr_username }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull image from Docker Hub
        run: docker pull wincheahken/tfcontainer:latest

      - name: Tag image for GHCR
        run: docker tag wincheahken/tfcontainer:latest ghcr.io/${{ github.event.inputs.ghcr_username }}/${{ github.event.inputs.ghcr_image }}:${{ github.event.inputs.ghcr_tag }}

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.event.inputs.ghcr_username }}/${{ github.event.inputs.ghcr_image }}:${{ github.event.inputs.ghcr_tag }}
